---
version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=letmein
      - DATABASE_HOST=database
    links:
      - database
    depends_on:
      - database

  database:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=letmein
      - POSTGRES_DB=coding_challenge
    image: postgres
